import json
import os
import random
import uuid
from datetime import datetime, timedelta, timezone

import requests


CLICKHOUSE_URL = os.getenv("CLICKHOUSE_URL", "http://clickhouse:8123")
CLICKHOUSE_USER = os.getenv("CLICKHOUSE_USER", "siem")
CLICKHOUSE_PASSWORD = os.getenv("CLICKHOUSE_PASSWORD", "ClickHousePass123!")
TOTAL_ALERTS = int(os.getenv("ALERT_SEEDER_TOTAL", "50"))

ATTACKER_IPS = [
    "203.0.113.5",
    "203.0.113.12",
    "198.51.100.20",
    "203.0.113.88",
]

RULES = {
    "brute_force_api": {
        "title": "API / SignalR Brute-Force Authentication Attempts",
        "mitre": ["T1110", "T1110.001"],
        "descriptions": [
            "Brute-force detected against API authentication endpoints",
            "Multiple failed authentication attempts from single IP",
        ],
    },
    "sql_injection_attempt": {
        "title": "SQL/NoSQL Injection Attempt Detected in Application Logs",
        "mitre": ["T1190", "T1059.007"],
        "descriptions": [
            "Union-based SQL injection payload detected in request path",
            "Database error pattern indicates probable SQL injection attempt",
        ],
    },
    "privilege_escalation_attempt": {
        "title": "Privilege Escalation or Unauthorized Admin Access Attempt",
        "mitre": ["T1068", "T1078.003", "T1548"],
        "descriptions": [
            "Forbidden access to privileged endpoint detected",
            "Repeated unauthorized access to admin resources",
        ],
    },
    "rate_limit_evasion": {
        "title": "Rate Limit Evasion - Anomalous Request Volume from Single IP",
        "mitre": ["T1595", "T1595.002"],
        "descriptions": [
            "Request volume exceeded rate-limiting thresholds",
            "Burst traffic pattern indicates automated probing activity",
        ],
    },
}


def random_ts_within_last_days(days: int = 7) -> datetime:
    now = datetime.now(timezone.utc)
    delta = timedelta(
        days=random.randint(0, days),
        hours=random.randint(0, 23),
        minutes=random.randint(0, 59),
        seconds=random.randint(0, 59),
        milliseconds=random.randint(0, 999),
    )
    return now - delta


def ch_ts(dt: datetime) -> str:
    return dt.strftime("%Y-%m-%d %H:%M:%S.%f")[:-3]


def status_plan():
    items = (
        [("new", "critical")] * 10
        + [("new", "high")] * 10
        + [("acknowledged", "medium")] * 15
        + [("resolved", random.choice(["low", "medium"])) for _ in range(10)]
        + [("false_positive", random.choice(["low", "medium"])) for _ in range(5)]
    )
    return items[:TOTAL_ALERTS]


def build_alert_row(status: str, severity: str):
    rule_id = random.choice(list(RULES.keys()))
    rule = RULES[rule_id]
    triggered_at = random_ts_within_last_days(7)
    acknowledged_at = None
    acknowledged_by = None

    if status in {"acknowledged", "resolved"}:
        acknowledged_at = triggered_at + timedelta(minutes=random.randint(5, 300))
        acknowledged_by = random.choice(["soc_analyst_1", "soc_analyst_2", "incident_bot"])

    row = {
        "alert_id": str(uuid.uuid4()),
        "fingerprint": str(uuid.uuid4()),
        "triggered_at": ch_ts(triggered_at),
        "rule_id": rule_id,
        "rule_title": rule["title"],
        "severity": severity,
        "description": random.choice(rule["descriptions"]),
        "source_ip": random.choice(ATTACKER_IPS),
        "user_id": random.choice(["admin", "svc-api", "user_023", "user_156", None]),
        "event_ids": [str(uuid.uuid4()) for _ in range(random.randint(1, 3))],
        "mitre_tags": rule["mitre"],
        "status": status,
        "acknowledged_by": acknowledged_by,
        "acknowledged_at": ch_ts(acknowledged_at) if acknowledged_at else None,
        "notes": random.choice(
            [
                "Seeded alert for Grafana validation",
                "Synthetic SOC alert for dashboard population",
                "Generated by alert-seeder",
            ]
        ),
    }
    return row


def to_sql_value(value):
    if value is None:
        return "NULL"
    if isinstance(value, list):
        return "[" + ", ".join(to_sql_value(v) for v in value) + "]"
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace("'", "\\'")
        return f"'{escaped}'"
    return str(value)


def make_insert_sql(rows):
    columns = [
        "alert_id",
        "fingerprint",
        "triggered_at",
        "rule_id",
        "rule_title",
        "severity",
        "description",
        "source_ip",
        "user_id",
        "event_ids",
        "mitre_tags",
        "status",
        "acknowledged_by",
        "acknowledged_at",
        "notes",
    ]
    values_sql = []
    for row in rows:
        values_sql.append(
            "(" + ", ".join(to_sql_value(row[col]) for col in columns) + ")"
        )
    return (
        "INSERT INTO siem.alerts ("
        + ", ".join(columns)
        + ") VALUES "
        + ", ".join(values_sql)
    )


def main():
    plan = status_plan()
    rows = [build_alert_row(status, severity) for status, severity in plan]
    sql = make_insert_sql(rows)

    response = requests.post(
        CLICKHOUSE_URL,
        params={"query": sql},
        auth=(CLICKHOUSE_USER, CLICKHOUSE_PASSWORD),
        timeout=30,
    )
    response.raise_for_status()

    print(
        json.dumps(
            {
                "seeded": len(rows),
                "statuses": {
                    "new": sum(1 for r in rows if r["status"] == "new"),
                    "acknowledged": sum(1 for r in rows if r["status"] == "acknowledged"),
                    "resolved": sum(1 for r in rows if r["status"] == "resolved"),
                    "false_positive": sum(1 for r in rows if r["status"] == "false_positive"),
                },
                "clickhouse_url": CLICKHOUSE_URL,
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
