apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: siem-lite

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - siem-parser-deployment.yaml
  - detection-engine-deployment.yaml
  - vector-aggregator-deployment.yaml
  - clickhouse-statefulset.yaml
  - redpanda-statefulset.yaml
  - services.yaml
  - hpa.yaml
  - networkpolicy.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: siem-lite
  environment: production

images:
  - name: siem-parser
    newTag: latest
  - name: detection-engine
    newTag: latest

# Подключение overlay для конкретного окружения:
#   kubectl apply -k deploy/k8s/overlays/production
#   kubectl apply -k deploy/k8s/overlays/staging
